# This program demonstrates the use of for loops with start, stop, and step parameters.

# The range function generates a sequence of numbers from start to stop, incrementing by step.
# Syntax: range(start, stop, step)

start = 0  # Starting value of the sequence
stop = 10  # Stopping value of the sequence (exclusive)
step = 1   # Step value (increment)

# Using a for loop to iterate over the sequence generated by range
for i in range(start, stop, step):
    print("Iteration for loop:", i)
print()
    
# This program demonstrates the use of while loops with a condition.
nb_times = 0
while nb_times < 5:
	print("Iteration while loop:", nb_times)
	nb_times += 1
